### ISSUE TITLE
Android Basics: Introduction to Room and Flow: 8. Create the ListAdapter

### ISSUE THREAD

**Issue by progdog-ru** [google-developer-training/android-basics-kotlin-bus-schedule-app#29]
at the end of this step there is a point 7: Now that you've set up the adapter, you're done integrating Room into the Bus Schedule app. Take a moment to run the app and you should see a list of arrival times. Tapping on a row should navigate to the detail screen.

The app doesn't start as fo this error:

```
2021-10-21 12:21:44.373 6418-6418/com.example.busschedule E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.busschedule, PID: 6418
    java.lang.IllegalStateException: Cannot access database on the main thread since it may potentially lock the UI for a long period of time.
        at androidx.room.RoomDatabase.assertNotMainThread(RoomDatabase.java:385)
        at androidx.room.RoomDatabase.query(RoomDatabase.java:441)
        at androidx.room.util.DBUtil.query(DBUtil.java:83)
        at com.example.busschedule.database.schedule.ScheduleDao_Impl.getAll(ScheduleDao_Impl.java:29)
        at com.example.busschedule.viewmodels.BusScheduleViewModel.fullSchedule(BusScheduleViewModel.kt:9)
        at com.example.busschedule.FullScheduleFragment.onViewCreated(FullScheduleFragment.kt:71)
        at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:2987)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:546)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
        at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
        at androidx.fragment.app.FragmentManager.dispatchViewCreated(FragmentManager.java:3065)
        at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:2988)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:546)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
        at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3072)
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:251)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:501)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:246)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1433)
        at android.app.Activity.performStart(Activity.java:7986)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3677)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8167)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

This error also affects the execution of step 9 - the beginning of this step.

**Comment by calren** [comment]
Thanks for pointing this out! This issue describes the same error https://github.com/google-developer-training/android-basics-kotlin-bus-schedule-app/issues/2, so we'll be closing this one in favor of that.

The issue linked above also has suggestions for potential ways to fix the error.
